### ISSUE TITLE
Requiring Internet connection to install dependency any time catkin_make is executed even when openni2 is already installed

### ISSUE THREAD

**Issue by ItsJas** [orbbec/ros_astra_camera#23]
This is blocking the catkin_make command any time when no Internet connection is available. To avoid this problem I deleted the lines in CMakeLists.txt  enabling the fetch and the download of the openni2 dependency from https://github.com/orbbec/OpenNI2.git . So it won't ask for it anymore once the driver is already installed and compiled for the first time.
A test would be added instead in order to check whether  openni2 is installed or not , if it is installed no need to install it again or even to look for it , if it's not then it should be installed .
Also it would be more convenient if the installation is possible offline by simply copying the package in the work_space, so the openni2 dependency should be added somehow to the hole package. 
It would be great if you fix this!

**Comment by ob-tim-liu** [comment]
the file is upstream of ros_astra_camera for deb package  release, so we must provider the sourcecode 
for openni2, if you can't download openni2 from orbbec-github,  pls use the filterlibray branch, which 
include the openni2 sourcecode . 



---------------------------------------------------------------------
刘华 
座机：0755-86329228
邮箱：liuhua@orbbec.com
手机：13603061506
深圳奥比中光科技有限公司 www.orbbec.com.cn 
地址：深圳市南山区粤兴三道8号中国地质大学产学研基地中地大楼A808
 
From: ItsJas
Date: 2017-03-31 19:22
To: orbbec/ros_astra_camera
CC: Subscribed
Subject: [orbbec/ros_astra_camera] Requiring Internet connection to install dependency any time catkin_make is executed even when openni2 is already installed (#23)
This is blocking the catkin_make command any time when no Internet connection is available. To avoid this problem I deleted the lines in CMakeLists.txt enabling the fetch and the download of the openni2 dependency from https://github.com/orbbec/OpenNI2.git . So it want ask for it anymore once the driver is already installed and compiled for the first time.
A test would be added instead in order to check whether openni2 is installed or not , if it is installed no need to install it again or even to look for it , if it's not then it should be installed .
Also it would be more convenient if the installation is possible offline by simply copying the package in the work_space, so the openni2 dependency should be added somehow to the hole package.
It would be great if you fix this!
